.PHONY: all bericht aufgabe_1 aufgabe_2 clean

all: bericht

bericht:
	$(MAKE) -C bericht all

aufgabe_1:
	$(MAKE) -C aufgabe_1 all

aufgabe_2:
	$(MAKE) -C aufgabe_2 all

clean:
	$(MAKE) -C aufgabe_1 clean
	$(MAKE) -C aufgabe_2 clean
	$(MAKE) -C bericht clean
